; https://www.autohotkey.com/docs/commands/ListView.htm
; https://www.autohotkey.com/docs/Variables.htm#BuiltIn

Gui +Resize ; Allow resizing of the GUI.
Gui, Font, s14 ; Set the font to a size I can actually read.

; Add a ListView control to the GUI.
Gui, Add, ListView, vTheListView r40 w1000, Category|Variable|Value|Description

; Populate the list view with all of AHK's default variables.
LV_Add("", "OS", "A_OSVersion", A_OSVersion, "The version of your operating system.")
LV_Add("", "OS", "A_ComSpec", A_ComSpec, "The path to your OS command interpreter.")
LV_Add("", "OS", "A_Temp", A_Temp, "The directory where temp files are stored.")
LV_Add("", "OS", "A_OSType", A_OSType, "The type of your operating system.")
LV_Add("", "OS", "A_Is64bitOS", A_Is64bitOS, "Are you running a 64-bit OS?")
LV_Add("", "OS", "A_PtrSize", A_PtrSize, "Pointer size in bytes.")
LV_Add("", "OS", "A_Language", A_Language, "The default language setting for the OS as a 4-digit code.")
LV_Add("", "OS", "A_ComputerName", A_ComputerName, "The name of this computer.")
LV_Add("", "User", "A_UserName", A_UserName, "The user name of the current user.")
LV_Add("", "OS", "A_WinDir", A_WinDir, "The Windows directory.")
LV_Add("", "OS", "A_ProgramFiles", A_ProgramFiles, "The Windows program files directory.")
LV_Add("", "User", "A_AppData", A_AppData, "The current user's application data directory.")
LV_Add("", "OS", "A_AppDataCommon", A_AppDataCommon, "Folder for application data common to all users.")
LV_Add("", "User", "A_Desktop", A_Desktop, "Current user's desktop folder.")
LV_Add("", "OS", "A_DesktopCommon", A_DesktopCommon, "Folder when items common to all users' desktops are stored.")
LV_Add("", "User", "A_StartMenu", A_StartMenu, "Current user's start menu folder.")
LV_Add("", "OS", "A_StartMenuCommon", A_StartMenuCommon, "Start menu items for all users.")
LV_Add("", "User", "A_Programs", A_Programs, "Start menu programs for current user.")
LV_Add("", "OS", "A_ProgramsCommon", A_ProgramsCommon, "Start menu programs for all users.")
LV_Add("", "User", "A_Startup", A_Startup, "Folder of stuff to run at startup for current user.")
LV_Add("", "OS", "A_StartupCommon", A_StartupCommon, "Folder of stuff to run at startup for all users.")
LV_Add("", "User", "A_MyDocuments", A_MyDocuments, "Current user's documents folder.")
LV_Add("", "User", "A_IsAdmin", A_IsAdmin, "Is the current user an administrator?")
LV_Add("", "OS", "A_ScreenWidth", A_ScreenWidth, "Width of the screen.")
LV_Add("", "OS", "A_ScreenHeight", A_ScreenHeight, "Height of the screen.")
LV_Add("", "OS", "A_ScreenDPI", A_ScreenDPI, "Pixels per logical inch.")
LV_Add("", "OS", "A_IPAddress1", A_IPAddress1, "IP address of your first network interface.")
LV_Add("", "Mouse", "A_Cursor", A_Cursor, "Type of mouse cursor being displayed.")
LV_Add("", "Mouse", "A_CaretX", A_CaretX, "Mouse x coordinate at text insertion point.")
LV_Add("", "Mouse", "A_CaretY", A_CaretY, "Mouse y coordinate at text insertion point.")
LV_Add("", "OS", "Clipboard", Clipboard, "Text contents of the clipboard.")
; LV_Add("", "OS", "ClipboardAll", ClipboardAll, "Entire contents of the clipboard.")
LV_Add("", "AHK", "ErrorLevel", ErrorLevel, "Error level set by last AHK command.")
LV_Add("", "OS", "A_LastError", A_LastError, "Last error returned from a DLL call.")
LV_Add("", "AHK", "true", true, "Builtin constant for true (value is 1).")
LV_Add("", "AHK", "false", false, "Builtin constant for false (value is 0).")
LV_Add("", "Loop", "A_Index", A_Index, "Current 1-based loop iteration count.")
LV_Add("", "Loop", "A_LoopFileName", A_LoopFileName, "Name of file when doing a files loop.")
LV_Add("", "Loop", "A_LoopRegName", A_LoopRegName, "Registry key when doing a registry loop.")
LV_Add("", "Loop", "A_LoopReadLine", A_LoopReadLine, "The read line when doing a file reading loop.")
LV_Add("", "Loop", "A_LoopField", A_LoopField, "The parsed field when doing a line parsing loop.")
LV_Add("", "Menu", "A_ThisMenuItem", A_ThisMenuItem, "The most recently selected custom menu item.")
LV_Add("", "Menu", "A_ThisMenu", A_ThisMenu, "The menu which A_ThisMenuItem belongs to.")
LV_Add("", "Menu", "A_ThisMenuItemPos", A_ThisMenuItemPos, "The 1-based position of A_ThisMenuItem within A_ThisMenu.")
LV_Add("", "Hotkey", "A_ThisHotkey", A_ThisHotkey, "The triggering string for currently activated hotkey.")
LV_Add("", "Hotkey", "A_PriorHotkey", A_PriorHotkey, "The triggering string for the previous activated hotkey.")
LV_Add("", "Hotkey", "A_TimeSinceThisHotkey", A_TimeSinceThisHotkey, "Milliseconds since this hotkey was triggered.")
LV_Add("", "Hotkey", "A_TimeSincePriorHotkey", A_TimeSincePriorHotkey, "Milliseconds since prior hotkey was triggered.")
LV_Add("", "Hotkey", "A_EndChar", A_EndChar, "The ending character used to trigger this hotstring.")
LV_Add("", "Keyboard", "A_PriorKey", A_PriorKey, "The last key that was pressed.")
LV_Add("", "AHK", "A_Space", A_Space, "A space character.") 
LV_Add("", "AHK", "A_Tab", A_Tab, "A tab character.") 
LV_Add("", "Script", "A_Args", A_Args, "Command-line args.") 
LV_Add("", "Script", "A_WorkingDir", A_WorkingDir, "Current working directory of this script.") 
LV_Add("", "Script", "A_ScriptDir", A_ScriptDir, "The directory where this script lives.") 
LV_Add("", "Script", "A_ScriptName", A_ScriptName, "The name of this script (including extension).") 
LV_Add("", "Script", "A_ScriptFullPath", A_ScriptFullPath, "The full path to this script.") 
LV_Add("", "Script", "A_ScriptHwnd", A_ScriptHwnd, "The id of the main window of this script (tray menu Open, not Gui)") 
LV_Add("", "Script", "A_LineNumber", A_LineNumber, "Currently executing line number in A_LineFile.") 
LV_Add("", "Script", "A_LineFile", A_LineFile, "The file in which line A_LineNumber is executing.") 
LV_Add("", "Script", "A_ThisFunc", A_ThisFunc, "Name of the current function.") 
LV_Add("", "Script", "A_ThisLabel", A_ThisLabel, "Name of the current label (aka, subroutine).") 
LV_Add("", "AHK", "A_AhkVersion", A_AhkVersion, "The version of the AHK interpreter that is running this script.") 
LV_Add("", "AHK", "A_AhkPath", A_AhkPath, "Path to the AHK interpreter executable.") 
LV_Add("", "AHK", "A_IsUnicode", A_IsUnicode, "Was AHK compiled to use Unicode?") 
LV_Add("", "Script", "A_IsCompiled", A_IsCompiled, "Is this a compiled (standalone) script?") 
LV_Add("", "Script", "A_ExitReason", A_ExitReason, "Why the script was asked to terminate.") 
LV_Add("", "Date/Time", "A_YYYY", A_YYYY, "Four-digit year.") 
LV_Add("", "Date/Time", "A_MM", A_MM, "Two-digit month, zero-padded.  Same as A_Mon") 
LV_Add("", "Date/Time", "A_DD", A_DD, "Two-digit day, zero-padded.  Same as A_MDay") 
LV_Add("", "Date/Time", "A_MMMM", A_MMMM, "Full name of the month.") 
LV_Add("", "Date/Time", "A_MMM", A_MMM, "Abbreviated name of the month.") 
LV_Add("", "Date/Time", "A_DDDD", A_DDDD, "Full name of the week day.") 
LV_Add("", "Date/Time", "A_DDD", A_DDD, "Abbreviated name of the week day.")
LV_Add("", "Date/Time", "A_WDay", A_WDay, "Numeric week day.  1-based; 1 is Sunday.") 
LV_Add("", "Date/Time", "A_YWeek", A_YWeek, "Year and week number combined (like 202050).") 
LV_Add("", "Date/Time", "A_Hour", A_Hour, "Two-digit hour, 0-24, zero-padded.") 
LV_Add("", "Date/Time", "A_Min", A_Min, "Two-digit minute, 0-59, zero-padded.") 
LV_Add("", "Date/Time", "A_Sec", A_Sec, "Two-digit second, 0-59, zero-padded.") 
LV_Add("", "Date/Time", "A_MSec", A_MSec, "Three-digit millisecond, 0-999, zero-padded.") 
LV_Add("", "Date/Time", "A_Now", A_Now, "Current time as timestamp.") 
LV_Add("", "Date/Time", "A_NowUTC", A_NowUTC, "Current time in UTC time zone as timestamp.") 
LV_Add("", "Date/Time", "A_TickCount", A_TickCount, "Number of milliseconds since this computer started.") 
LV_Add("", "Script", "A_IsSuspended", A_IsSuspended, "Are hotkeys for this script suspended?") 
LV_Add("", "Script", "A_IsPaused", A_IsPaused, "Is this script paused?") 
LV_Add("", "Script", "A_IsCritical", A_IsCritical, "Is this thread marked as critical?") 
LV_Add("", "AHK", "A_BatchLines", A_BatchLines, "Number of milliseconds between batches of lines.  Affects overall speed of script.") 
LV_Add("", "AHK", "A_ListLines", A_ListLines, "Is ListLines enabled?") 
LV_Add("", "AHK", "A_TitleMatchMode", A_TitleMatchMode, "How titles are matched: 1 (at start), 2 (anywhere), 3 (exact), or RegEx") 
LV_Add("", "AHK", "A_DetectHiddenWindows", A_DetectHiddenWindows, "Should window/title queries find hidden windows?") 
LV_Add("", "AHK", "A_DetectHiddenText", A_DetectHiddenText, "Is invisible text seen when searching for windows?") 
LV_Add("", "AHK", "A_AutoTrim", A_AutoTrim, "Is auto trim enabled?") 
LV_Add("", "AHK", "A_StringCaseSense", A_StringCaseSense, "Not sure exactly what this does.") 
LV_Add("", "Files", "A_FileEncoding", A_FileEncoding, "The file encoding used for various file commands.") 
LV_Add("", "AHK", "A_FormatInteger", A_FormatInteger, "How to format integers: H/h (hex) or D (decimal).") 
LV_Add("", "AHK", "A_FormatFloat", A_FormatFloat, "How to format floating point decimals.") 
LV_Add("", "AHK", "A_SendMode", A_SendMode, "The current send mode.") 
LV_Add("", "AHK", "A_SendLevel", A_SendLevel, "The current send level.") 
LV_Add("", "AHK", "A_StoreCapsLockMode", A_StoreCapsLockMode, "Something to do with CapsLock.") 
LV_Add("", "Keys", "A_KeyDelay", A_KeyDelay, "The delay in milliseconds between sending keystrokes.") 
LV_Add("", "Keys", "A_KeyDuration", A_KeyDuration, "How long a key is held down.") 
LV_Add("", "Keys", "A_KeyDelayPlay", A_KeyDelayPlay, "Milliseconds between keys for SendPlay.") 
LV_Add("", "Keys", "A_KeyDurationPlay", A_KeyDurationPlay, "Duration of keystrokes for SendPlay.") 
LV_Add("", "Windows", "A_WinDelay", A_WinDelay, "Delay in milliseconds after each window command.") 
LV_Add("", "Controls", "A_ControlDelay", A_ControlDelay, "Delay in milliseconds after each control command.") 
LV_Add("", "Mouse", "A_MouseDelay", A_MouseDelay, "Delay in ms between mouse commands.") 
LV_Add("", "Mouse", "A_MouseDelayPlay", A_MouseDelayPlay, "Delay in ms between mouse commands using SendPlay.") 
LV_Add("", "Mouse", "A_DefaultMouseSpeed", A_DefaultMouseSpeed, "Default mouse speed.") 
LV_Add("", "Coordinates" , "A_CoordModeToolTip", A_CoordModeToolTip, "What the coordinate mode is for tool tips.") 
LV_Add("", "Coordinates", "A_CoordModePixel", A_CoordModePixel, "Coordinate mode for pixels (?).") 
LV_Add("", "Mouse", "A_CoordModeMouse", A_CoordModeMouse, "The coordinate mode for Mouse* commands.") 
LV_Add("", "Coordinates", "A_CoordModeCaret", A_CoordModeCaret, "Not sure.") 
LV_Add("", "Coordinates", "A_CoordModeMenu", A_CoordModeMenu, "Not sure.") 
LV_Add("", "Registry", "A_RegView", A_RegView, "The current registry view (set by SetRegView).") 
LV_Add("", "Script", "A_IconHidden", A_IconHidden, "Is this script's tray icon hidden?") 
LV_Add("", "Script", "A_IconTip", A_IconTip, "Tooltip for this script's tray icon.")
LV_Add("", "Script", "A_IconFile", A_IconFile, "Path of custom tray icon file.")
LV_Add("", "Script", "A_IconNumber", A_IconNumber, "Number of icon in A_IconFile used for custom tray icon.")
LV_Add("", "User", "A_TimeIdle", A_TimeIdle, "Number of milliseconds user has been idle.")
LV_Add("", "User", "A_TimeIdlePhysical", A_TimeIdlePhysical, "Number of milliseconds user has been idle (ignoring automated input).")
LV_Add("", "User", "A_TimeIdleKeyboard", A_TimeIdleKeyboard, "Milliseconds since last keyboard input.")
LV_Add("", "User", "A_TimeIdleMouse", A_TimeIdleMouse, "Milliseconds since last mouse input.")
LV_Add("", "GUI", "A_DefaultGui", A_DefaultGui, "Name of current thread's default GUI.")
LV_Add("", "GUI", "A_DefaultListView", A_DefaultListView, "ListView name or hwnd that LV_* commands operate on by default.")
LV_Add("", "GUI", "A_Gui", A_Gui, "Name of the GUI that launched the current thread.")
LV_Add("", "GUI", "A_GuiControl", A_GuiControl, "Name of the GUI control that launched the current thread.")
LV_Add("", "GUI", "A_GuiWidth", A_GuiWidth, "Width of this GUI in pixels.")
LV_Add("", "GUI", "A_GuiHeight", A_GuiHeight, "Height of this GUI in pixels.")
LV_Add("", "GUI", "A_GuiX", A_GuiX, "The GUI x coordinate of a context menu or drag/drop event.")
LV_Add("", "GUI", "A_GuiY", A_GuiY, "The GUI y coordinate of a context menu or drag/drop event.")
LV_Add("", "GUI", "A_GuiEvent", A_GuiEvent, "The type of event that launched the current thread.")
LV_Add("", "GUI", "A_GuiControlEvent", A_GuiControlEvent, "The type of event that launched the current thread.")
LV_Add("", "GUI", "A_EventInfo", A_EventInfo, "Extra info about a GUI event (or Windows message).")
LV_ModifyCol() ; Autosize all columns to fit data.

Gui, Show 


; This gets called when the GUI is resized.
GuiSize:
	width := A_GuiWidth - 15
	height := A_GuiHeight - 15
	GuiControl, Move, theListView, w%width% h%height%
return


